### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by galloprc** [MisaOgura/MRNet#7]
hello，when I running your code ,it will error
line 138, in <listcomp> for weight in pos_weights]

TypeError: __init__() got an unexpected keyword argument 'pos_weight'

Can you tell me how to correct him?

**Comment by galloprc** [comment]
I find the problem
criterions = [nn.BCEWithLogitsLoss(pos_weight=weight) \
should be  modify
criterions = [nn.BCEWithLogitsLoss(weight=weight) \

**Comment by MisaOgura** [comment]
Hi @galloprc, please make sure that the version of pytorch used in your environment is 0.1.0 or later, as specified in [README](https://github.com/MisaOgura/MRNet#1-setup-an-environment).

Please note that `weight` and `pos_weight` are different parameters for `BCEWithLogitsLoss` ([official doc](https://pytorch.org/docs/stable/nn.html#torch.nn.BCEWithLogitsLoss)) and will change the behaviour of the loss function if used interchangeably.

Many thanks.
